apiVersion: v2
name: fluentbit
description: A Helm chart for FluentBit CRs
maintainers:
- name: Karen Danielyan
  email: kar.danielyan@gmail.com
- name: Radagast The Brown
  email: radagast@cloudwizz.org
type: application
version: 0.1.0
