apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "olleh.fullname" . }}-nginx-conf
  labels:
    {{- include "olleh.labels" . | nindent 4 }}
data:
  {{- range $path, $_ := .Files.Glob .Values.nginxConfs }}
  {{ base $path }}: |
    {{- $.Files.Get $path | nindent 4 }}
  {{- end }}
