apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "olleh.fullname" . }}-index-html
  labels:
    {{- include "olleh.labels" . | nindent 4 }}
data:
  {{ base .Values.indexHtml }}: |
    {{- .Files.Get .Values.indexHtml | nindent 4 }}
