apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFluentBitConfig
metadata:
  labels:
    {{- include "fluentbit.labels" . | nindent 4 }}
  name: fluentbit-config
spec:
  filterSelector:
    matchLabels:
      {{- toYaml .Values.fluentbit.matchLabels | nindent 6 }}
  inputSelector:
    matchLabels:
      {{- toYaml .Values.fluentbit.matchLabels | nindent 6 }}
  outputSelector:
    matchLabels:
      {{- toYaml .Values.fluentbit.matchLabels | nindent 6 }}
  service:
    httpServer: true
    parsersFile: parsers.conf
